version: '3'

volumes:
  {{cookiecutter.project_slug}}_ci_postgres_data: {}
  {{cookiecutter.project_slug}}_ci_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: {{cookiecutter.project_slug}}_ci_django
    container_name: {{cookiecutter.project_slug}}_ci_django
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app:z
      - ../{{cookiecutter.project_slug}}:/app/{{cookiecutter.project_slug}}:z
    env_file:
      - ./.envs/.local/.django.example
      - ./.envs/.local/.postgres.example
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: {{cookiecutter.project_slug}}_ci_postgres
    container_name: {{cookiecutter.project_slug}}_ci_postgres
    volumes:
      - {{cookiecutter.project_slug}}_ci_postgres_data:/var/lib/postgresql/data
      - {{cookiecutter.project_slug}}_ci_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres.example

  docs:
    image: {{cookiecutter.project_slug}}_ci_docs
    container_name: {{cookiecutter.project_slug}}_ci_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django.example
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./riso:/app/riso:z
    ports:
      - '9000:9000'
    command: /start-docs

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: {{cookiecutter.project_slug}}_ci_mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: {{cookiecutter.project_slug}}_ci_redis

  celeryworker:
    <<: *django
    image: {{cookiecutter.project_slug}}_ci_celeryworker
    container_name: {{cookiecutter.project_slug}}_ci_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: {{cookiecutter.project_slug}}_ci_celerybeat
    container_name: {{cookiecutter.project_slug}}_ci_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: {{cookiecutter.project_slug}}_ci_flower
    container_name: {{cookiecutter.project_slug}}_ci_flower
    ports:
      - '5555:5555'
    command: /start-flower
